{% set name = "pytdc" %}
{% set version = "1.1.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 279b4cfd0c556e62781bbf099d0eb6c530de04afae6d4953a0041105c723429b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=38.6.0
  run:
    - python >={{ python_min }}
    - fuzzywuzzy
    - numpy
    - pandas >=1.1.4
    - scikit-learn >=0.21.3
    - tqdm
    - scipy
    - networkx
    - rdkit >=2020.03.6
    - requests
    - seaborn

test:
  requires:
    - python {{ python_min }}
  imports:
    - tdc
    - tdc.generation
    - tdc.multi_pred
    - tdc.single_pred

about:
  home: https://github.com/mims-harvard/TDC
  summary: Therapeutics Data Commons
  license: MIT
  license_family: MIT
  # Upstream issue for license file: https://github.com/mims-harvard/TDC/issues/2
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
