{% set name = "pytdc" %}
{% set version = "0.1.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyTDC-{{ version }}.tar.gz
  sha256: cad4ad4e8e4017aa1bdc92a0164fe69b46af3f5829938a2c08ffea11351a62e4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=38.6.0
  run:
    - python >=3.6
    - fuzzywuzzy
    - numpy
    - pandas >=1.1.4
    - scikit-learn >=0.21.3
    - tqdm
    - scipy
    - networkx
    - rdkit >=2020.03.6
    - requests

test:
  imports:
    - tdc
    - tdc.generation
    - tdc.multi_pred
    - tdc.single_pred

about:
  home: https://github.com/mims-harvard/TDC
  summary: Therapeutics Data Commons
  license: MIT
  license_family: MIT
  # Upstream issue for license file: https://github.com/mims-harvard/TDC/issues/2
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
